### ISSUE TITLE
Only items in albums are exported

### ISSUE THREAD

**Issue by teoteo** [abentele/PhotosExporter#12]
I’ve created a small library for testing with 8 images.
<img width="1117" alt="01-library" src="https://user-images.githubusercontent.com/789650/115041692-10148380-9ed3-11eb-93c1-04de0b0a2367.png">

3 of them are in Album0; 1 of them is Album1
<img width="1117" alt="02-albums" src="https://user-images.githubusercontent.com/789650/115041719-17d42800-9ed3-11eb-9bee-83a2b92a78e3.png">

I’ve exported the library and only 4 images are exported.
<img width="901" alt="03-exported" src="https://user-images.githubusercontent.com/789650/115041752-21f62680-9ed3-11eb-90ad-02e00e6ea461.png">

If is it by design, I suggest to write in [Readme.md](https://github.com/abentele/PhotosExporter/blob/master/Readme.md)

An **improvement** could be also creating a folders structure to allow the export of all images.
I think something like
```
-year
--month
---day
```

but a custom structure could be placed in configuration file ~/Library/Application Support/PhotosExporter/PhotosExporter.yaml with something like this
```
%year%-%month%-%day%
```
or
```
%mediaType%-%year%-%month%
```
or
```
%keyword%-%year%
```

**Comment by RhetTbull** [comment]
@teoteo I know I already mentioned [osxphotos](https://github.com/RhetTbull/osxphotos) to you but will describe here how osxphotos handles this as something similar might be useful for PhotosExporter:

osxphotos includes a full templating system that allows user to specify directory, filename, and metadata (such as keywords) with templates similar to what you describe.

For example, the examples you gave can be executed in osxphotos thusly:
`osxphotos export /path/to/export --directory "{created.year}/{created.month}/{created.dd}"`

`osxphotos export /path/to/export --directory "{media_type}/{created.year}/{created.month}"`

You can even specify custom values for the media types:
`osxphotos export /path/to/export --directory "{media_type,photo=foto;video=vidéo;time_lapse=vidéo_accélérée}/{created.year}/{created.month}"`

`osxphotos export /path/to/export --directory "{keyword}/{created.year}"`

You can also specify default values, for example, for photos that have no keyword:

`osxphotos export /path/to/export --directory "{keyword,NoKeyword}/{created.year}"`
In this case, any photos that don't have keywords go to the "NoKeyword" directory.

osxphotos also exports all images, not just those in albums, and works on any photos library even if it's not the system library.

This system can also be used for specifying the filename and also for configuring exported metadata (e.g. embedding metadata into the EXIF data of the exported image or the Finder tags)

For example, add the word "Favorite" to all photos which are favorites and use exiftool to apply all metadata (keywords, persons, etc) from the Photos library to the exported image's EXIF data:

`osxphotos export /path/to/export --directory "{created.year}/{created.month}/{created.dd}" --filename "{favorite?Favorite-{original_name},{original_name}}" --exiftool`

I'm focused on developing osxphotos so don't have time to contribute to PhotosExporter but if the developer is interested, they can look at the grammar for the "mini language" osxphotos uses [here](https://github.com/RhetTbull/osxphotos/blob/master/osxphotos/phototemplate.tx).  I've put a lot of thought into making the template system very flexible.

**Comment by RhetTbull** [comment]
If you're interested in doing something similar for PhotosExporter, I recommend a PEG parser as it's very flexible.  I initially implemented the osxphotos template engine using regular expressions but it was very cumbersome.  I switched to [textx](http://textx.github.io/textX/stable/) which is a configurable PEG parser for python.  There are similar options for Swift such as [Patterns](https://github.com/kareman/Patterns).

**Comment by abentele** [comment]
@teoteo yes, the current implementation only exports images that are in albums. The previous implementation which used the MLMediaLibrary API exported all photos. After switching to the PhotoKit API I simply ignored the photos which are not in any album. For me it's a known issue which should be fixed.

@teoteo, @RhetTbull regarding customization of directory structure: yes, it could be helpful for some people. But it's currently not on my personal wish list - my opinion is that it's sufficient to have a good default directory structure; also it would add additional complexity to configuration and implementation. Maybe I add some customization features in future. If you like this idea, please add another issue (I don't like tickets with more than one concern).

**Comment by abentele** [comment]
@RhetTbull  Thanks for your suggestions.

**Comment by abentele** [comment]
now photos not assigned to any collection are also exported. Not yet implemented suggestion for configurable folder structure, because the current solution is sufficient for _my_ workflow: I always assign photos to albums after they are imported.
