### ISSUE TITLE
macOS 14.6.1 SystemLibraryPath not more available

### ISSUE THREAD

**Issue by lubbo** [abentele/PhotosExporter#18]
In macOS 14.6.1 the file Containers/com.apple.photolibraryd/Data/Library/Preferences/com.apple.photolibraryd.plist desn't contain SystemLibraryPath anymore.
It's not possible to retrieve photo library

**Comment by lubbo** [comment]
There is a new PLLibraryBookmarkManagerBookmarksByPath key that contains all used libraries...
The first should be the most recent... not sure about that...

**Comment by lubbo** [comment]
group.com.apple.photolibraryd.private.plist contains the SystemLibraryPath

**Comment by abentele** [comment]
fixed, see linked pull request
