### ISSUE TITLE
redundant code execution?

### ISSUE THREAD

**Issue by britiscurious** [abentele/PhotosExporter#2]
Why is the initExport overridden here?

https://github.com/abentele/PhotosExporter/blob/443cb12e95d9a09d807d00c8f22992cd00308fa8/PhotosExporter/exporter/SnapshotPhotosExporter.swift#L70

Looks like this is just causing a call of recreateInProgressFolder and within the override the same again. (But I'm a Swift beginner.)

**Comment by abentele** [comment]
you are right, the method can be removed.
