### ISSUE TITLE
LIcense?

### ISSUE THREAD

**Issue by adamf** [abentele/PhotosExporter#4]
Hi! I'd love to use this code in an project I'm working on, but the code doesn't have a license. Is it open source under something like the MIT license? Thanks!

**Comment by abentele** [comment]
It's under MIT license. I will document this.
If you want, let me know which kind of project you are working on?

**Comment by abentele** [comment]
Added a license file to repository.

**Comment by adamf** [comment]
@abentele thanks! I'm looking to use some of the code to make a MacOS status bar app that reads your Photos metadata and recreates the albums in Google Photos, and keeps that in sync.

**Comment by abentele** [comment]
@adamf extending the PhotosExporter app with a status bar UI including a feature to configure the export tasks and automatic scheduling of the export tasks is on top of my wish list. Also many people will find sync to Google Photos very useful. What do you think about working together on an App that has such kind of an UI, with multi-target export (starting with file system export and google photos sync). We can discuss it by mail: abentele.github@icloud.com
